name: End to End

on:
  pull_request:

jobs:
  end-to-end:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    env:
      NODE_ENV: test
      STRIPE_KEY: ${{ secrets.STRIPE_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Build the stack
        run: docker compose -f ./cypress/docker-compose.yml up -d

      - name: Wait for containers stabilize
        run: sleep 10

      - name: Show Docker Logs
        run: docker compose -f ./cypress/docker-compose.yml logs

      - name: Debug containers
        run: |
          docker ps
          docker logs wongames_api || true

      - name: Inspect API container
        run: |
          docker inspect wongames_api || true

      - name: Waiting Strapi Server
        run: |
          docker run --rm \
            --network container:wongames_api \
            jwilder/dockerize \
            -wait http://localhost:1337/admin \
            -timeout 120s \
            -wait-retry-interval 5s

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run Cypress
        run: npm run test:e2e:ci
